### ISSUE TITLE
Extend terminal support

### ISSUE THREAD

**Issue by lunaryorn** [lunaryorn/mdcat#12]
Figure out whether other terminal emulators support iTerm2 features and extend the list of supported terminals accordingly.

**Comment by vinipsmaker** [comment]
The terminal I use also supports images, but it uses its own escape sequences: https://github.com/billiob/terminology

Maybe it's simply enough that you guys could implement it.

**Comment by lunaryorn** [comment]
I'd appreciate a pull request, to be honest; I can't test that terminal myself.

**Comment by PerBothner** [comment]
DomTerm (https://domterm.org) supports not only inline images and links but also inline html.
In fact following works pretty well as an mdcat substitute:

    cmark -t html common-mark.md | domterm hcat

The main issue with the above pipeline is the relative URLs aren't handled well at this point (though I'm thinking of the best way to deal with it).

The `domterm hcat` command is basically trivial: In addition to terminal detection (a quick-and-dirty way to do that is to check for a `DOMTERM` environment variable) it just wraps the output in a simple escape sequence:

    \033]72;HTML_DATA\007

I don't know Rust but it seems mdcat could easily add DomTerm support by wrapping the output of pulldown-cmark with the above-mentioned escape sequence.  Preferably you'd want to convert URLs to `data:` URLs - at the very least relative URLs.

**Comment by lunaryorn** [comment]
@PerBothner I can add support for DomTerm to the inline HTML code—though I don't have much time and would prefer a pull request.

But I wonder whether I need to:  If DomTerm supports HTML why not use one of the many Markdown-to-HTML converters instead?  🤔 

These tools produce leverage the full syntax of HTML and normally produce much better output than `mdcat` with its limitation to ASCII formatting.  In fact it seems to me that on DomTerm `alias mdcat="pandoc | domterm hcat|` would do a much better job than `mdcat` itself 🙂

**Comment by PerBothner** [comment]
Two reasons I can think of:

1. If you intend mdcat as a general portable tool for "do as good a job as you can" to display MarkDown on the current terminal, it would be better if it would do the right thing without the user having to create a wrapper script to handle both DomTerm and "other terminals".

2. There is the issue of how to handle relative URLs - especially for images - in the source.  I'm working on a `--base-url=URL` option for `domterm hcat` to resolve these URLs. However, it would be more robust to translate images to `data:` URLs.  One reason if you're ssh'd to a different computer than the one running the display - the file may not be available to the local browser.  Another is if the image is modified or removed: A "refresh" could change previous output. 

Perhaps `domterm hcat` could have an option to translate local (or all) image URLs to `data:` URLs but that would add quite of bit of complexity to `domterm hcat`.  (That command does not current parse or scrub the HTML - that is done by the browser part of DomTerm.)

Now whether these reasons are strong enough to add DomTerm support to mdcat is a different issue.  Ideally, yes, but given limited resources I understand if you don't make it top priority :-)

**Comment by aeosynth** [comment]
to add another terminal, kitty created its own graphics protocol:

https://sw.kovidgoyal.net/kitty/index.html
https://sw.kovidgoyal.net/kitty/graphics-protocol.html

perhaps you could use the ranger tui file manager as a rosetta stone; it supports drawing images in iterm2, terminology, urxvt, and kitty

https://github.com/ranger/ranger
https://github.com/ranger/ranger/blob/master/ranger/ext/img_display.py

**Comment by lunaryorn** [comment]
Thanks but I won’t add that myself.  I don’t have the time.

I’m closing this issue; I don’t intend to add further terminal emulators myself.

Please open a pull request to add support for this terminal emulator if you like.
