### ISSUE TITLE
Image Scaling with Kitty

### ISSUE THREAD

**Issue by Fidgetcetera** [lunaryorn/mdcat#124]
This is mostly an inconsistency between how kitty normally behaves with images, and how it seems to work in mdcat. 

if i mdcat a file that has an image too wide for the current kitty window, the image just doesn't load. however, if i `kitty icat` that same image, it shows up, scaled down to fit the terminal window appropriately.

is this intended mdcat behavior?

**Comment by lunaryorn** [comment]
I don't think so, but then I don't use kitty and didn't write this part of mdcat.  

I guess it should scale down, and I think it used to when this feature was initially contributed to mdcat.

I guess I broke it when refactoring or perhaps by updating the image crate but I don't know why or how.  In any case I don't have time to fix it; if you'd like it fixed please do open a pull request.

**Comment by fspillner** [comment]
@Fidgetcetera Thanks for reporting this. I've opened a PR aiming to fix your issue in general. You may have a look in my PR and test my fix. Additionally, the resizing may not work as expected and check my PR for the details.

**Comment by lunaryorn** [comment]
@fspillner @Fidgetcetera I released 0.17.1 which should fix this issue.
