### ISSUE TITLE
Usage with lesspipe/lessfilter

### ISSUE THREAD

**Issue by ukch** [lunaryorn/mdcat#135]
I am trying to use your tool as a filter for [less](http://www.greenwoodsoftware.com/less/) using [lesspipe](https://www-zeuthen.desy.de/~friebel/unix/lesspipe.html). Doing a simple test on the provided sample file works mostly, but the link at the end is rendered as follows:

```
Source: 8;;https://pixabay.com/de/einhorn-regenbogen-magische-magie-2087450/^GPixabay8;;^G, CC0
```

I assume this is probably an issue with less not supporting whatever feature you are using here, but I was wondering if it would be possible for you to add a user-friendly fallback for this case, like you do with images?

Side note: mdcat's image feature doesn't work on my system, but it has a nice fallback, so I'm OK with that. The fallback renders correctly in less, but I assume the full image functionality would probably not.

**Comment by lunaryorn** [comment]
mdcat prints an inline link here. A fallback exists but isn't used here; you probably use a terminal which supports inline links, but mdcat doesn't detect the intermediate less which messes links up.

Perhaps there's a flag to `less` which tells it to either drop unknown OSC codes or pass them through to the terminal emulator.  There's also an internal `--ansi-only` flag for `mdcat`, but so far it's only used in mdcat's own tests and I consider it not for public use, but please do open a pull request to change that.  And finally you can open a pull request to extend `mdcat::terminal::TerminalCapabilities::detect` to detect lesspipe and automatically fallback to Ansi only formatting.

In any case I'll not fix this myself; I don't use lesspipe and personally just don't enough to spend my own time on this. 

But please do open a pull request if have a fix for this.

**Comment by nabramovitz** [comment]
Have you tried "mdcat <files> | less -r"?

**Comment by dgolds** [comment]
less -r works for me on iTerm2 on mac!

Thanks. That would be nice to have in the readme

**Comment by lunaryorn** [comment]
Closing in favour of #152.  Pull requests welcome.
