### ISSUE TITLE
Any chance to make it nicer in VSCode?

### ISSUE THREAD

**Issue by AEiosApp** [lunaryorn/mdcat#151]
Hi, really like this tool, btw it doesn't looks nice in VSCode terminal of my Mac.
Any chance or suggestion to make it nicer?

![image](https://user-images.githubusercontent.com/19554725/85960624-94107580-b96a-11ea-9be6-7506ceeca50d.png)

**Comment by lunaryorn** [comment]
I'm not sure what I'm supposed to see in that screenshot, and what changes you'd like to have 🤷🏼‍♂️

In any case if you'd like to change the output you'll need to make a pull request because for my part I'm ok with how it looks currently and won't change it myself.
