### ISSUE TITLE
Document how to integrate it with cat

### ISSUE THREAD

**Issue by gigs94** [lunaryorn/mdcat#161]
Just a suggestion to add a help file that could be installed in *nix systems that would integrate with the original cat you could write functions (if in bash):

```
orig_cat=$(type -P cat);
cat () {
    for i in $*
    do
        if [[ ${i: -3} == ".md" ]]
        then
            mdcat $i
        else 
            ${orig_cat} $i
        fi
    done
}
```

**Comment by lunaryorn** [comment]
Thanks but I won't do that.

**Comment by cagdassalur** [comment]
I was checking the documentation excatly for this, turned to issues hoping for a solution. Maybe this has a place in documentation..
