### ISSUE TITLE
can't cat concatenate markdown?

### ISSUE THREAD

**Issue by qlcom** [lunaryorn/mdcat#162]
you should better change the description.

**Comment by lunaryorn** [comment]
Is this some kind of joke?

**Comment by qlcom** [comment]
> Is this some kind of joke?

No.

You should change the description.

**Comment by lunaryorn** [comment]
Seriously?

**Comment by qlcom** [comment]
a better description for this program.

**Comment by lunaryorn** [comment]
I'm sorry but this is not the way it works.

**Comment by qlcom** [comment]
> this is not the way it works.

how does it work?

**Comment by lunaryorn** [comment]
You'll find out, but not here.  I'm sorry but I do not find this conversation valuable use of my time, nor will I change the description of this repository.
