### ISSUE TITLE
Feature request: Possibility to hide image dep behind a feature

### ISSUE THREAD

**Issue by LiquidityC** [lunaryorn/mdcat#163]
Hi, I'm using mdcat in a terminal application for rendering *in application* help files.

Some of my users run the application on headless servers. These sometimes lack support and libraries for image rendering which causes problems when compiling my application on those machines due to the image dependency having additional dependencies on OS libraries.

I haven't taken a look at the code so I have no clue how impactful this might be on the code base. Perhaps it's not even an option?

Anyways, that's my request.

For reference this is the application in question: [blightmud](https://github.com/liquidityc/blightmud)

**Comment by lunaryorn** [comment]
With reqwest disabled mdcat links statically against musl; what OS libraries are you talking about?

In any case if you'd like to change mdcat's build setup you'll need to make a pull request; personally I'm fine with how it is and won't make any changes myself.

**Comment by LiquidityC** [comment]
I'm not certain really. I just got the message directly. I'll get some details and work on a PR if I get more details. Thanks for the response.
