### ISSUE TITLE
fails to build on every non-x86/arm platform since ureq

### ISSUE THREAD

**Issue by q66** [lunaryorn/mdcat#173]
6fbb20a805be769d1b49503d053f2378a4547747 switched to `ureq`, which seems to be using `rustls`, which uses `ring`, which doesn't build on any platforms other than windows/mac/linux x86/arm

**Comment by lunaryorn** [comment]
I am sorry, yet it still builds on all platforms I care for.  I'll not do anything about this, and close this issue hence.

**Comment by q66** [comment]
well then, thanks for nothing

**Comment by ericonr** [comment]
@lunaryorn would you accept a toggleable feature for `ureq`, and adding back the curl fallback? Or just omit the image download functionality completely if `ureq` is disabled.

**Comment by lunaryorn** [comment]
> well then, thanks for nothing

I am sorry but I do not think that I owe you anything.

**Comment by lunaryorn** [comment]
@ericonr Feel free to open a pull request for the latter; I'll consider it if it's not too invasive.

**Comment by q66** [comment]
i'm not implying that, it's perfectly fair - it just means another package to drop

**Comment by lunaryorn** [comment]
Drop from what?  Those platforms you listed are the major ones aren't they? What platform do you specifically care about? Wouldn't it be wise to make ring build on that platform?

**Comment by q66** [comment]
drop from our distribution, on some architectures; in this case we specifically care about POWER/PowerPC family, but there's more out there (RISC-V, s390x, etc...)

I in fact *did* at one point port ring to all POWER targets (it was fully passing testsuite and so on), but upstream is hostile and will not accept any new target support unless it's corporate sponsored (i.e. if you submit a PR you basically get asked for money - there doesn't even seem to be an option of making it a tier 2 target maintained by community), and since it has no portable fallbacks for its assembly implementations of crypto algos (which it should, but it doesn't) there's just no way out

it is problematic in other ways as well (e.g. they yank all older versions from the registry, and if you want to be able to use them you again get asked for commercial sponsorship, which is problematic considering the API is not stable)

so all that I can do is discourage upstreams from relying on it

but of course, if you don't want to, that is your decision, it is your project after all

**Comment by lunaryorn** [comment]
These architectures are rather obscure with regards to mdcat's supposed target audience, aren't they?  I thought powerpc on consumer systems died with Intel Macs, and you wouldn't run mdcat on an embedded system would you?  Did anyone really use mdcat on a PowerPC or sparc?

As for ring, I believe accusations as strong as those need some source or proof, lest they be understood as mere gossip.

In any case mdcat does not rely on ring, it merely uses it by proxy. Concerns about ring are better taken to those projects which directly depend on ring, which in this case appears to be rustls as I understand.  If these projects consider ring fit for their purposes I will not judge otherwise.

That said I am happy to reconsider ureq if a feasible alternative can be found, however any change in that direction needs to come as a pull request. 

I'm not willing to compromise on static linking offered by ureq for the sake of niche platforms, though.

**Comment by q66** [comment]
there are currently modern high-performance POWER based workstations available (i am, in fact, typing from one, and it works exactly as a regular desktop, has all the usual applications and desktop environments, etc.) and people still use their older hardware as well; regardless of your perceived suitability of a platform, a tool like this doesn't have much of a reason to rely on things that are not portable, and if it does, it's rather strange

regarding ring, there is proof scattered all over the issue tracker, as well as emails sent to me when I tried upstreaming the port - but that's not the point

when you use rust, indirect dependencies are direct dependencies, since everything is built at once and there is no such thing as using external dependencies from the system - if there was, i would have considered just running a downstream fork, but patching every single application with their specific versions of dependencies is just not feasible

anyway, as i said, i don't really care enough about mdcat, so i'm not trying to push you into anything - our distro compiles all software for all platforms, and with the most recent version update i ran into a failure on the buildserver, that's all; the only notable thing is that our documentation browser (which is packaged for all platforms) was using mdcat, but it will not be using it any longer in its next release, and there isn't anything else depending on mdcat in the repository, so if it remains non-portable i will just ditch it and call it a day

**Comment by lunaryorn** [comment]
I respectfully disagree with most of what you said and would rather prefer evidence consolidated but scattered, but I believe we need not discuss this any further.

This tool works everywhere I need it to work; the rest is a matter of pull requests.
