### ISSUE TITLE
Any chance this utility published as a library?

### ISSUE THREAD

**Issue by tailhook** [lunaryorn/mdcat#18]
The plan is to use it to provide some markdown formatting in command-line utilities.

What do you think?

**Comment by lunaryorn** [comment]
@tailhook I can make a lib crate of it, and expose the entry function, but I'd rather not like to think about a useful API or make any promises about compatibility.  Honestly, to me that's too much effort for such a small tool.

**Comment by lunaryorn** [comment]
If you have a concrete idea where you'd like to use this tool as a library then we can look into it, but I won't publish mdcat as a library just because I could.

**Comment by tailhook** [comment]
Sorry for being unresponsive. The idea I had in mind is:
1. Use it in complex command-line utilities, athough I'm not sure that clap will adopt it
2. Use it in [vagga](https://vagga.readthedocs.org) where users define commands and commands are often non trivial, requiring some descriptions

However, I'll probably hack some prototype before actually doing any work in this library.

**Comment by lunaryorn** [comment]
@tailhook I do not believe that either of these should use mdcat, and personally I'd not like to have to consider these use cases in mdcat.  

I'd just like to use mdcat to quickly view and navigate a markdown README in my terminal for looking up some stuff, and that's basically the entire scope of this tool.  Having to consider other use cases is already too much work for me to be honest.

**Comment by tailhook** [comment]
Basically I need some markdown to "escape-codes" formatter. So do you recommend just fork this code?

**Comment by lunaryorn** [comment]
Yes, perhaps, if it suits your needs I don't mind if you fork it under the terms of its license.  But it's in an early stage, and doesn't format all well.

Personally, tho, I think better formats exist to provide help.  If you'd like to stick to text at least go for man pages which—unlike mdcat—provide some basic cross-referencing—pandoc can turn markdown into man pages—but I believe a good HTML manual works way better than an `--help` or `man` ever do.

**Comment by lunaryorn** [comment]
@tailhook Okay, I made `mdcat` a library crate because it helps me as well to get an idea of what I'm doing.  So the next release provides an `extern crate mdcat` with a minimal interface.

Feel free to use, but please understand that I make no guarantees about that interface yet and that I'll change the interface whenever I need it to make my changes to `mdcat`.

**Comment by tailhook** [comment]
> Feel free to use, but please understand that I make no guarantees about that interface yet and that I'll change the interface whenever I need it to make my changes to mdcat.

No problem. Just make sure to bump major version every time you break the API :)

**Comment by lunaryorn** [comment]
@tailhook I'll adhere to semantic versioning, so as long as `mdcat` is still at 0.x please do not assume the API is stable.  It may change at any time, even in patch releases. I'll won't make any promises before 1.0 🙂
