### ISSUE TITLE
When using pagination images aren't displayed

### ISSUE THREAD

**Issue by arandomliz** [lunaryorn/mdcat#195]
When using `mdcat` on the sample files (i.e. `common-marks.md`) using `mdcat -p common-marks.md` one will not see any images in the file.

Interestingly using `less -rX` will show images, but the location of these will brake when scrolling. Is there any solution to this? I'm using the kitty terminal version 0.23.1

**Comment by lunaryorn** [comment]
No there's no solution. It'd require a pager which understands image sequences. Less doesn't, and I'm not aware of any other pager 🤷

**Comment by arandomliz** [comment]
Ah oke. I thought something like that might be the reason for it. That's kinda sad actually :/

**Comment by lunaryorn** [comment]
> And I dont really have the time to try myself on something like that.

Well then it's gonna be sad for the time being :shrug:
