### ISSUE TITLE
First character in title is crossed

### ISSUE THREAD

**Issue by shiroyasha** [lunaryorn/mdcat#21]
Example screenshot for the 'CommonMark' header:

![screen shot 2018-02-14 at 9 15 28 pm](https://user-images.githubusercontent.com/1779493/36225837-4373e406-11cc-11e8-92c3-f927a35081bb.png)

Some info that might help:

- iTerm2 Build 3.1.5
- 15pt Monaco font
- Built in Pasted color scheme
- tmux inside of a vagrant ubuntu image

**Comment by shiroyasha** [comment]
Found some similar issues on the internet https://github.com/schachmat/wego/issues/5.

The issue seems to be related to the Monaco font as I can reproduce the issue with `echo "\u2504CommonMark"` in my terminal.

**Comment by lunaryorn** [comment]
@shiroyasha I think the font's at fault… u2504 is a standard box character which should not extend into the next character, and no other font I tried (Menlo, Fira Mono, Source Code Pro, Hasklig, Courier New, and Pragmata Pro) behaves this way.

I don't think there's anything to fix in mdcat here.
