### ISSUE TITLE
tab completion not working in zsh

### ISSUE THREAD

**Issue by meredrica** [lunaryorn/mdcat#214]
hi!

Tab completion for file names seems to be broken in zsh
steps:
```
cd /tmp/
echo 'some text' > README.md
```
then try to autocomplete the README.md

```sh
$ mdcat --version
mdcat 0.29.0
```

**Comment by lunaryorn** [comment]
I can't ho you; I do not use zsh.

I'm sorry but you need to debug and fix this yourself.  Pull requests are welcome.

**Comment by lunaryorn** [comment]
@meredrica I think I've found the issue, see #216 

I'll make a new release with this fix soon; I'd appreciate testing 🙂

**Comment by lunaryorn** [comment]
@meredrica 0.30.0 is out, with a change which hopefully fixes this issue.  Let me know if you still have issues with completion.

**Comment by meredrica** [comment]
Hi!

Will do asap and get back to you

**Comment by meredrica** [comment]
@swsnr can confirm, working now.
