### ISSUE TITLE
Feature request: Color output when paginated (with less, for example)

### ISSUE THREAD

**Issue by j1mmie** [lunaryorn/mdcat#39]
When using `mdcat` with `less`, colors are lost. For example:

`curl https://raw.githubusercontent.com/lunaryorn/mdcat/master/README.md | mdcat | less`

![image](https://user-images.githubusercontent.com/4650220/45380016-7667f580-b5b6-11e8-965c-12313e917be1.png)

Note that `mdcat` correctly provides full color support for this document if `less` is omitted:

`curl https://raw.githubusercontent.com/lunaryorn/mdcat/master/README.md | mdcat`

![image](https://user-images.githubusercontent.com/4650220/45379975-5c2e1780-b5b6-11e8-84e4-7f63747be2bc.png)

The behavior occurs regardless of whether `less -r` or `less -R` are used.

Confirmed the same behavior exists in iTerm2:

![image](https://user-images.githubusercontent.com/4650220/45380124-cba40700-b5b6-11e8-8150-02c79c1b6faa.png)

Color support when piped to `less` would be great!

**Comment by lunaryorn** [comment]
`mdcat` won't print terminals if piped; that's like most commands behave as far as I know.

You can make it print colours with `mdcat --colour=yes`, but it'll still loose some terminal specific formatting, ie, links or iTerm2 jump marks.

I'll merge a PR that makes `mdcat` always print colours or adds more sophisticated behaviour w/ `less`, but personally I don't care a lot to be honest.  I almost never use `less`; I just scroll in iTerm directly and use jump marks to go back and forth.

**Comment by j1mmie** [comment]
Thanks for taking a look - yeah it's not high priority by any means. Maybe some others will find this request and +1 it, but until then there are sufficient workarounds

**Comment by j1mmie** [comment]
For posterity, the correct command to get colors in less then is:

`curl https://raw.githubusercontent.com/lunaryorn/mdcat/master/README.md | mdcat --colour=yes | less -r`
