### ISSUE TITLE
Update reqwest dependency

### ISSUE THREAD

**Issue by mmstick** [lunaryorn/mdcat#47]
Each project that uses this crate is being forced to use reqwest 0.8.8, which uses an older version of the openssl crate that won't compile on most Linux distributions today. Any Linux distribution with libssl 1.1.1 or higher is unable to compile this.

**Comment by lunaryorn** [comment]
master uses reqwest 0.9 already 🙂 so I’ll close this issue.

**Comment by mmstick** [comment]
> master uses reqwest 0.9 already :slightly_smiling_face: so I’ll close this issue.

Make sure to publish a new release. There's some applications that I can't yet compile or package yet (`imag`) because the version on Crates.io isn't using reqwest 0.9.

**Comment by lunaryorn** [comment]
There are just two reverse dependencies according to crates.io, one of which still at a really old version of mdcat, and no folks from those crates or from any Linux Distel or anywhere ever said anything. I wasn’t aware that anyone actually cared for a release. 🙂

 I’ll publish a new one, but it won’t be this year.  I’m sorry 😔 but family time is just way more important to me than this thing here.  I
Anyhow, it won’t happen before Christmas.

**Comment by mmstick** [comment]
> There are just two reverse dependencies according to crates.io

I'm not sure if [imag](https://github.com/matthiasbeyer/imag) is published on Crates.io.

> or from any Linux Distro or anywhere ever said anything

Well now you have :stuck_out_tongue_closed_eyes: I'm the maintainer of Pop!\_OS. I can't build imag at the moment for 18.10 without forking it to replace the dependency at the moment.

**Comment by lunaryorn** [comment]
> I can't build imag at the moment for 18.10 without forking it to replace the dependency at the moment.

You’ll have to do this then 🤷‍♂️ I’m sorry but with Christmas ahead I just don’t want to take time for this currently.
