### ISSUE TITLE
Allow file list as input

### ISSUE THREAD

**Issue by rien333** [lunaryorn/mdcat#54]
`cat` allows you to print multiple files:
```(bash)
$ cat file1.txt file2.txt ...
# file 1 output
# file 2 output
...
```

Would be cool if `mdcat` would be compatible with `cat` in this way. A neat addition of this feature would be that you can cat files that adhere to a regex pattern, so you can for example cat all notes pertaining to some author:
```(bash)
$ mdcat Smith*.md
```

**Comment by lunaryorn** [comment]
I’ll merge a pull request which adds this feature.

**Comment by tsonev7** [comment]
@lunaryorn are you still doing this? :)
I can take this task if you don't have time to implement it.

**Comment by lunaryorn** [comment]
I [never said that **I** would do this](https://github.com/lunaryorn/mdcat/issues/54#issuecomment-451738832).

If anyone wants this they’ll have to make a pull request.
