### ISSUE TITLE
Support for Tilix

### ISSUE THREAD

**Issue by Depau** [lunaryorn/mdcat#60]
Tilix is known to support hyperlinks in terminal, according to [this gist](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda). However mdcat 0.12.1 is not displaying links inline.

Is it possible to add support for Tilix's features?

**Comment by lunaryorn** [comment]
I have inline links with tilix 1.8.1.  

Tilix uses VTE under the hood; mdcat supports inline links in all VTE based terminals.

I don’t know why it’s not working in your case, maybe your tilix version is too old, maybe you disabled the osc8 links feature when installing mdcat, … 🤷‍♂️ but I don’t think mdcat’s at fault here, so I’ll close this issue.
