### ISSUE TITLE
Support images in Kitty

### ISSUE THREAD

**Issue by rien333** [lunaryorn/mdcat#65]
[Kitty](https://sw.kovidgoyal.net/kitty/kittens/icat.html?highlight=images) is a modern terminal emulator that can [display images](https://sw.kovidgoyal.net/kitty/kittens/icat.html?highlight=images). It is likely one of the only crossplatform terminal applications that can do so (at least easily and out-of-the-box). It's probably as good as iTerm in displaying images, and possibly quite similar in how you interface ( [termpdf](https://github.com/dsanson/termpdf) for example supports both). 

I might try and implement this myself one day, not sure if I can find the time though.

**Comment by lunaryorn** [comment]
> I might try and implement this myself one day, not sure if I can find the time though.

I can't either, particularly not for a terminal I don't use.  

Thanks for the suggestion but you'll need to open a pull request to get this done.

**Comment by lunaryorn** [comment]
Closed by #104

**Comment by rien333** [comment]
So cool!
