### ISSUE TITLE
Rely to cat if not .md file?

### ISSUE THREAD

**Issue by zbraniecki** [lunaryorn/mdcat#7]
If `mdcat` could rely the command to `cat` in case the file is not an `.md` file then `mdcat` could be just used as an alias for `cat`.

**Comment by lunaryorn** [comment]
Thanks for your suggestion 😊

I’m not sure, though; I’d like to keep this tool simple and focused on Markdown.

Can’t you wrap a shell script around cat and mdcat for this purpose?

**Comment by aatxe** [comment]
This issue inspired me a bit, and I wrote a little function for the fish shell to wrap cat:
https://github.com/aatxe/dotfiles/blob/master/fish/functions/cat.fish

**Comment by lunaryorn** [comment]
@aatxe Cool 👍 I'm using Fish as well.  Are you aware of the `string` built-in?  You can use `string match -rq -- '^-' $arg` instead of `echo $arg | grep` and save a sub-process 🙂

**Comment by zbraniecki** [comment]
I'm on .zsh, and I'm afraid that having to write a script per shell is ok, but not the easiest route. :) And since `mdcat` doesn't really handle non-md files, I think that relying to the default handler shouldn't increase complexity?

But up to the package author. Feel free to close this issue if that's not a feature you're interested in adding.

**Comment by lunaryorn** [comment]
@zbraniecki I think I'll close this then.

I understand that a custom script isn't very convenient; but I'd rather like to keep it simple to be able to maintain it in my limited time.  Perhaps if anyone can come up with a pull request that doesn't add too much code, I'd take a look, but personally I don't need this feature—I use less and lesspipe for other files—so I'd rather not spend my time on this.  I'm sorry.
