### ISSUE TITLE
Fallback if strikethrough isn't supported

### ISSUE THREAD

**Issue by lunaryorn** [lunaryorn/mdcat#73]
iTerm2 and Terminal.app don't support strikethrough text; we should have a good fallback.

Currently the text just renders like normal text which isn't so good probably.

Follow up from #71.

**Comment by norman-abramovitz** [comment]
ITerm2 does support strikethrough in version 3.3.7 at least.   I am wondering if it is a profile setting that might need to be changed.

<img width="490" alt="Screen Shot 2019-12-31 at 4 35 15 PM" src="https://user-images.githubusercontent.com/13754664/71636872-ae4fdd80-2beb-11ea-9446-69500f14cb27.png">

**Comment by norman-abramovitz** [comment]
It actually looks like pulldown_cmark supports strikethrough already

<img width="526" alt="Screen Shot 2019-12-31 at 4 45 04 PM" src="https://user-images.githubusercontent.com/13754664/71636948-1eab2e80-2bed-11ea-89e0-71ec7e8f0439.png">
