### ISSUE TITLE
Render hyperlinks as hyperlinks in iTerm

### ISSUE THREAD

**Issue by Turbo87** [lunaryorn/mdcat#8]
according to https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda it should be possible to render hyperlinks as actual hyperlinks in iTerm

**Comment by lunaryorn** [comment]
Woa thanks for making me aware 👍  It’s even documented at https://www.iterm2.com/documentation-escape-codes.html but I totally missed it.

Will add this, that’s so cool 😍

**Comment by lunaryorn** [comment]
@Turbo87 Added; many thanks for the suggestion!
