### ISSUE TITLE
inline links in gnome-terminal on Fedora 29 VTE_VERSION=5404

### ISSUE THREAD

**Issue by dustymabe** [lunaryorn/mdcat#88]
Inline links don't seem to be working for me in gnome-terminal on Fedora 29 (`gnome-terminal-3.30.3-1.fc29.x86_64`). I grabbed the [0.13.0](https://github.com/lunaryorn/mdcat/releases/download/mdcat-0.13.0/mdcat-0.13.0-x86_64-unknown-linux-musl.tar.gz) release and tried to `mdcat README.md` and I still see the links below the text:

```
• ☐ Figure out a better way to show HTML GH-3[31].
• ☐ CommonMark extensions: Footnotes GH-1[32].
• ☐ CommonMark extensions: Tables GH-2[33].
• ☐ Ignore soft wraps and wrap inline text a column limit instead GH-4[34].

[31]: https://github.com/lunaryorn/mdcat/issues/3 
[32]: https://github.com/lunaryorn/mdcat/issues/1 
[33]: https://github.com/lunaryorn/mdcat/issues/2 
[34]: https://github.com/lunaryorn/mdcat/issues/4
```

My VTE environment variable is: 

```
$ env | grep VTE
VTE_VERSION=5404
```

**Comment by lunaryorn** [comment]
I'm sorry to hear that `mdcat` isn't working as expected, but I don't think I have the time to fix this.     You'll need to fix this yourself.

**Comment by dustymabe** [comment]
> I'm sorry to hear that `mdcat` isn't working as expected, but I don't think I have the time to fix this. You'll need to fix this yourself.

No worries. It's possible I'm doing something wrong. Wondering if anyone else is having this same problem.
