### ISSUE TITLE
AUR Package

### ISSUE THREAD

**Issue by wezm** [lunaryorn/mdcat#9]
Just a heads up that I've created a [PKGBUILD for the Arch User Repository](https://aur.archlinux.org/packages/mdcat/) to make it easy for Arch Linux users to install `mdcat` with their system package manager. You may like to add a note to the README like the one I added for [alt](https://github.com/uptech/alt#arch-linux).

**Comment by lunaryorn** [comment]
@wezm Thanks; I added a link to the AUR page to the README.
