### ISSUE TITLE
Support Pandoc-style fenced code attributes

### ISSUE THREAD

**Issue by Seirdy** [lunaryorn/mdcat#96]
The `fenced_code_attributes` Pandoc extension allows code blocks to contain attributes
describing HTML classes and attributes. The Pandoc manual has a
[section](https://pandoc.org/MANUAL.html#fenced-code-blocks) on this feature.

The main reason why this has been a problem for me is that Pandoc's markdown output
formats my code blocks like so:

```` markdown
``` {.rust}
fn main() {
		println!("Hello world!");
}
```
````

Simply handling the curly-brace syntax would be enough. Handling more complex
attributes like `{#mycode .haskell .numberLines startFrom="100"}` would be great as
well, but that'd be a bit more work.

**Comment by lunaryorn** [comment]
mdcat only supports commonmark.  I’m sorry but this is out of scope.

I suggest you reimplement mdcat on top of Pandoc’s API to use its special Markdown dialect.
