### ISSUE TITLE
pulldown-cmark outdated

### ISSUE THREAD

**Issue by matthiasbeyer** [lunaryorn/mdcat#99]
Hi,

I tried to update the pulldown-cmark dependency for this crate, but it seems to be non-trivial.

Could you please update the dependency and release a new version? :smiley: would be awesome! If you care I can share my effort, but it is not very much and you'll probably reproduce it in a few minutes.

**Comment by lunaryorn** [comment]
@matthiasbeyer I'm sorry but I don't think I will.  I can't see anything in the changelog of this version that'd affect me, and I just don't have time (nor motiviation, tbh) to update just for the sake of updating.

**Comment by matthiasbeyer** [comment]
I understand your reasons. I will have a closer look then, thanks for your time and developing this crate. I'll leave this open so others can see it.
